INSERT INTO Revision VALUES (1, "Outline");
INSERT INTO Revision VALUES (2, "Draft");
INSERT INTO Revision VALUES (3, "1st Edit");
INSERT INTO Revision VALUES (4, "2nd Edit");
INSERT INTO Revision VALUES (5, "Done");
INSERT INTO Section VALUES (1, "Part I", "The first part, in which things happen", 1, 1);
INSERT INTO Section VALUES (2, "Part II", "The second part, in which more things happen", 2, 2);
INSERT INTO Section VALUES (3, "Chapter 1", "The first chapter, in the first part", 3, 1);
INSERT INTO Section VALUES (4, "Chapter 2", "The second chapter, in which things happen", 4, 1);
INSERT INTO Scene VALUES (1, "Police Station", "Leon shoots holden during a Voigt-Kampff test.", 1, 3, 1);
INSERT INTO Scene VALUES (2, "Tyrell Office", "Deckard administers the Voigt-Kampff test to Rachael.", 2, 3, 2);
INSERT INTO Scene VALUES (3, "Sebastian's Apartment", "Deckard faces Pris and Roy.", 3, 4, 1);
INSERT INTO Character VALUES (1, "Rick Deckard", "Deckard", "A blade runner, and the main character.", "Maybe a replicant. Probably.");
INSERT INTO Character VALUES (2, "Roy Batty", "Roy", "Replicant, crazy.", "Has some sweet boxers.");
INSERT INTO Character VALUES (3, "Rachael", "", "Replicant, mother of bubble girl.", "Has the name of a dude.");
INSERT INTO CharacterInScene VALUES (1, 2);
INSERT INTO CharacterInScene VALUES (3, 2);
INSERT INTO CharacterInScene VALUES (1, 3);
INSERT INTO CharacterInScene VALUES (2, 3);